//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualScene.PresentationComponents.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualScene.PresentationComponents.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Arc camera.
        /// </summary>
        public static string Title_Add_Arc_Camera {
            get {
                return ResourceManager.GetString("Title_Add_Arc_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cube.
        /// </summary>
        public static string Title_Add_Cube {
            get {
                return ResourceManager.GetString("Title_Add_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Free camera.
        /// </summary>
        public static string Title_Add_Free_Camera {
            get {
                return ResourceManager.GetString("Title_Add_Free_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sphere.
        /// </summary>
        public static string Title_Add_Sphere {
            get {
                return ResourceManager.GetString("Title_Add_Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera: {0}.
        /// </summary>
        public static string Title_Camera_N {
            get {
                return ResourceManager.GetString("Title_Camera_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Title_Cancel {
            get {
                return ResourceManager.GetString("Title_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Title_Close {
            get {
                return ResourceManager.GetString("Title_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        public static string Title_Cube {
            get {
                return ResourceManager.GetString("Title_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Title_File_name {
            get {
                return ResourceManager.GetString("Title_File_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Type.
        /// </summary>
        public static string Title_Geometry_Type {
            get {
                return ResourceManager.GetString("Title_Geometry_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Title_Import {
            get {
                return ResourceManager.GetString("Title_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import 3D model.
        /// </summary>
        public static string Title_Import_3D_model {
            get {
                return ResourceManager.GetString("Title_Import_3D_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import 3D model.
        /// </summary>
        public static string Title_Import3D_model {
            get {
                return ResourceManager.GetString("Title_Import3D_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Title_OK {
            get {
                return ResourceManager.GetString("Title_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        public static string Title_Sphere {
            get {
                return ResourceManager.GetString("Title_Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Title_Stage {
            get {
                return ResourceManager.GetString("Title_Stage", resourceCulture);
            }
        }
    }
}
