//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualScene.BusinessComponents.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualScene.BusinessComponents.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with material &quot;{0}&quot; not found..
        /// </summary>
        internal static string Message_AddMaterials_File_with_material_N_not_found {
            get {
                return ResourceManager.GetString("Message_AddMaterials_File_with_material_N_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during the operation &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string Message_Error_occured_during_the_operation_M_N {
            get {
                return ResourceManager.GetString("Message_Error_occured_during_the_operation_M_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found..
        /// </summary>
        internal static string Message_LoadGeometry_File_N_not_found {
            get {
                return ResourceManager.GetString("Message_LoadGeometry_File_N_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string Message_Not_defined {
            get {
                return ResourceManager.GetString("Message_Not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum bitDepth value: {0}.
        /// </summary>
        internal static string Message_ValidateSceneArguments_Maximum_bitDepth_value_N {
            get {
                return ResourceManager.GetString("Message_ValidateSceneArguments_Maximum_bitDepth_value_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum bitDepth value: {0}.
        /// </summary>
        internal static string Message_ValidateSceneArguments_Minimum_bitDepth_value_N {
            get {
                return ResourceManager.GetString("Message_ValidateSceneArguments_Minimum_bitDepth_value_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum height value: {0}.
        /// </summary>
        internal static string Message_ValidateSceneArguments_Minimum_height_value_N {
            get {
                return ResourceManager.GetString("Message_ValidateSceneArguments_Minimum_height_value_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width value: {0}.
        /// </summary>
        internal static string Message_ValidateSceneArguments_Minimum_width_value_N {
            get {
                return ResourceManager.GetString("Message_ValidateSceneArguments_Minimum_width_value_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stage of the scene is not initialized.
        /// </summary>
        internal static string Title_Add_The_stage_of_the_scene_is_not_initialized {
            get {
                return ResourceManager.GetString("Title_Add_The_stage_of_the_scene_is_not_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Title_Navigation_Camera {
            get {
                return ResourceManager.GetString("Title_Navigation_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Stage.
        /// </summary>
        internal static string Title_Save_Stage {
            get {
                return ResourceManager.GetString("Title_Save_Stage", resourceCulture);
            }
        }
    }
}
