//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualScene.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualScene.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation strategy cannot be null..
        /// </summary>
        internal static string Message_Calculation_strategy_cannot_be_null {
            get {
                return ResourceManager.GetString("Message_Calculation_strategy_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene-entity already exists in the stage..
        /// </summary>
        internal static string Message_Scene_entity_already_exists_in_the_stage {
            get {
                return ResourceManager.GetString("Message_Scene_entity_already_exists_in_the_stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene-entity does not exists in the stage..
        /// </summary>
        internal static string Message_Scene_entity_does_not_exists_in_the_stage {
            get {
                return ResourceManager.GetString("Message_Scene_entity_does_not_exists_in_the_stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeInfo cannot be created for null.
        /// </summary>
        internal static string Message_TypeInfo_cannot_be_created_for_null {
            get {
                return ResourceManager.GetString("Message_TypeInfo_cannot_be_created_for_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of teeth and outside diameter.
        /// </summary>
        internal static string Title_By_number_of_teeth_and_outside_diameter {
            get {
                return ResourceManager.GetString("Title_By_number_of_teeth_and_outside_diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of teeth and pitch diameter.
        /// </summary>
        internal static string Title_By_number_of_teeth_and_pitch_diameter {
            get {
                return ResourceManager.GetString("Title_By_number_of_teeth_and_pitch_diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        internal static string Title_Cube {
            get {
                return ResourceManager.GetString("Title_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Polygon.
        /// </summary>
        internal static string Title_Custom_Polygon {
            get {
                return ResourceManager.GetString("Title_Custom_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        internal static string Title_Cylinder {
            get {
                return ResourceManager.GetString("Title_Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        internal static string Title_Disk {
            get {
                return ResourceManager.GetString("Title_Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Title_Empty {
            get {
                return ResourceManager.GetString("Title_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow Cylinder.
        /// </summary>
        internal static string Title_Hollow_Cylinder {
            get {
                return ResourceManager.GetString("Title_Hollow_Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        internal static string Title_Sphere {
            get {
                return ResourceManager.GetString("Title_Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spur gear.
        /// </summary>
        internal static string Title_Spur_gear {
            get {
                return ResourceManager.GetString("Title_Spur_gear", resourceCulture);
            }
        }
    }
}
