//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualScene.DataComponents.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualScene.DataComponents.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type &quot;{0}&quot; was expected by the following type was loaded: &quot;{1}&quot;..
        /// </summary>
        public static string Message_A_type_N_was_expected_by_the_following_type_was_loaded_M {
            get {
                return ResourceManager.GetString("Message_A_type_N_was_expected_by_the_following_type_was_loaded_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity cannot be saved because it is empty.
        /// </summary>
        public static string Message_Archive_Entity_cannot_be_saved_because_it_is_empty {
            get {
                return ResourceManager.GetString("Message_Archive_Entity_cannot_be_saved_because_it_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive entry entity is empty for path &quot;{0}&quot;.
        /// </summary>
        public static string Message_Archive_entry_entity_is_empty_for_path_N {
            get {
                return ResourceManager.GetString("Message_Archive_entry_entity_is_empty_for_path_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive entry entity-type is empty for path &quot;{0}&quot;.
        /// </summary>
        public static string Message_Archive_entry_entity_type_is_empty_for_path_N {
            get {
                return ResourceManager.GetString("Message_Archive_entry_entity_type_is_empty_for_path_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive entry object cannot be deserialized: &quot;{0}&quot;.
        /// </summary>
        public static string Message_Archive_entry_object_cannot_be_deserialized_N {
            get {
                return ResourceManager.GetString("Message_Archive_entry_object_cannot_be_deserialized_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry elements is defined in the archive path.
        /// </summary>
        public static string Message_Archive_No_entry_elements_is_defined_in_the_archive_path {
            get {
                return ResourceManager.GetString("Message_Archive_No_entry_elements_is_defined_in_the_archive_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity information is not defined for the entry &quot;{0}&quot;.
        /// </summary>
        public static string Message_Entity_information_is_not_defined_for_the_entry_N {
            get {
                return ResourceManager.GetString("Message_Entity_information_is_not_defined_for_the_entry_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity-type information is not defined for the entry &quot;{0}&quot;.
        /// </summary>
        public static string Message_Entity_type_information_is_not_defined_for_the_entry_N {
            get {
                return ResourceManager.GetString("Message_Entity_type_information_is_not_defined_for_the_entry_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was found when a directory was expected in &quot;{0}&quot;.
        /// </summary>
        public static string Message_File_was_found_when_a_directory_was_expected_in_N {
            get {
                return ResourceManager.GetString("Message_File_was_found_when_a_directory_was_expected_in_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with the stage does not exists..
        /// </summary>
        public static string Message_File_with_the_stage_does_not_exists {
            get {
                return ResourceManager.GetString("Message_File_with_the_stage_does_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path for the entity is not defined.
        /// </summary>
        public static string Message_Folder_path_for_the_entity_is_not_defined {
            get {
                return ResourceManager.GetString("Message_Folder_path_for_the_entity_is_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null-packer is executed for {0}.
        /// </summary>
        public static string Message_Null_packer_is_executed_for_N {
            get {
                return ResourceManager.GetString("Message_Null_packer_is_executed_for_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the stage is invalid..
        /// </summary>
        public static string Message_Save_Name_of_the_stage_is_invalid {
            get {
                return ResourceManager.GetString("Message_Save_Name_of_the_stage_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive &quot;{0}&quot; with a stage cannot be processed due to the error &quot;{1}&quot;.
        /// </summary>
        public static string Message_The_archive_N_with_a_stage_cannot_be_processed_due_to_the_error_M {
            get {
                return ResourceManager.GetString("Message_The_archive_N_with_a_stage_cannot_be_processed_due_to_the_error_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive &quot;{0}&quot; with a stage might be currupted &quot;{1}&quot;.
        /// </summary>
        public static string Message_The_archive_N_with_a_stage_might_be_currupted_M {
            get {
                return ResourceManager.GetString("Message_The_archive_N_with_a_stage_might_be_currupted_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation is found by the entity does not need it: &quot;{0}&quot;.
        /// </summary>
        public static string Message_Transformation_is_found_by_the_entity_does_not_need_it_N {
            get {
                return ResourceManager.GetString("Message_Transformation_is_found_by_the_entity_does_not_need_it_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive entry-type is empty for path &quot;{0}&quot;.
        /// </summary>
        public static string StageFileSystemDataAdapter_UnArchive_Archive_entry_type_is_empty_for_path___0_ {
            get {
                return ResourceManager.GetString("StageFileSystemDataAdapter_UnArchive_Archive_entry_type_is_empty_for_path___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the stage.
        /// </summary>
        public static string Title_Load_the_stage {
            get {
                return ResourceManager.GetString("Title_Load_the_stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the stage.
        /// </summary>
        public static string Title_Save_the_stage {
            get {
                return ResourceManager.GetString("Title_Save_the_stage", resourceCulture);
            }
        }
    }
}
