//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualScene.DataComponents.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualScene.DataComponents.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data-adapter for the type &quot;{0}&quot; is not registered..
        /// </summary>
        public static string Message_A_data_adapter_for_the_type_N_is_not_registered {
            get {
                return ResourceManager.GetString("Message_A_data_adapter_for_the_type_N_is_not_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was found when a directory was expected in &quot;{0}&quot;.
        /// </summary>
        public static string Message_File_was_found_when_a_directory_was_expected_in_N {
            get {
                return ResourceManager.GetString("Message_File_was_found_when_a_directory_was_expected_in_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the stage is invalid..
        /// </summary>
        public static string Message_Save_Name_of_the_stage_is_invalid {
            get {
                return ResourceManager.GetString("Message_Save_Name_of_the_stage_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the stage.
        /// </summary>
        public static string Title_Save_Save_the_stage {
            get {
                return ResourceManager.GetString("Title_Save_Save_the_stage", resourceCulture);
            }
        }
    }
}
